# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: primary
  polling_interval: 0.1.seconds
  message_retention: 1.day


# solid_cableの公式ドキュメントの内容でdatabase.ymlに記載する内容を誤ってcable.ymlに記載してしまったのでコメントアウト
# production:
#   primary: &primary_production
#     <<: *default
#     database: app_production
#     username: app
#     password: <%= ENV["APP_DATABASE_PASSWORD"]
#   cable:
#     <<: *primary_production
#     database: app_production_cable
#     migrations_paths: db/cable_migrate




